Overview Page API
cuongtv-smartosc/template-fastapi pull request #26
Opened 2022-08-22 10:22 UTC by cuongtv-smartosc

2022-08-24 06:58 UTC, namvhsmart requested changes

2022-08-24 06:58 UTC, namvhsmart commented on app/common/util.py
> +def get_chart(data, search, dict_lable, label):
get_pie_chart

2022-08-24 06:58 UTC, namvhsmart commented on app/common/util.py
> +        "colors": ["#0072DB", "#469BFF", "#AAAFC7", "#50CC65"],
Color

2022-08-24 06:58 UTC, namvhsmart commented on app/common/util.py
>      if q:
chart.py

2022-08-24 06:58 UTC, namvhsmart commented on app/api/v1/Overview/sale_type_stats_router.py
> +    data = (
Chuyển vào service

2022-08-24 06:58 UTC, namvhsmart commented on tests/factories/electric_vehicle.py
> +    forklift_pdi_status = factory.Iterator(
Random

2022-08-24 06:58 UTC, namvhsmart commented on tests/factories/sale_information.py
> +    sale_type = factory.Iterator(
Random

2022-08-24 06:58 UTC, namvhsmart commented on tests/test_overview_page.py
> +        data = res["data"]
data= res.get("data").get("data")

2022-08-24 06:58 UTC, namvhsmart commented on tests/test_overview_page.py
> +        assert data["datasets"]["values"] == [6, 6, 6, 5, 5, 5]
Thay data mẫu

2022-08-30 02:52 UTC, namvhsmart requested changes

2022-08-30 02:52 UTC, namvhsmart commented on app/common/chart.py
> +    if search == "sale_type":
Sửa lại

2022-08-30 02:52 UTC, namvhsmart commented on tests/test_overview_page.py
> +            sale_type="inventory_useds",
inventory_used

2022-08-30 02:52 UTC, namvhsmart commented on app/services/over_view_page.py
> +label_sale_type = ["Rent", "Sold", "Inventory (Used)", "Inventory (New)"]
Bỏ

2022-08-30 02:52 UTC, namvhsmart commented on app/services/over_view_page.py
> +    check_data = list(SALE_TYPE_LABEL.keys())
Ko cần

2022-08-30 02:52 UTC, namvhsmart commented on app/services/over_view_page.py
> +        fps,
"forklift_pdi_status"

2022-08-30 02:52 UTC, namvhsmart commented on app/services/over_view_page.py
> +def contract_expire_report(
Bỏ

2022-08-30 02:52 UTC, namvhsmart commented on app/models/charger.py
> -from sqlalchemy import Column, DateTime, ForeignKey, String
Tạo PR mới

2022-08-30 02:52 UTC, namvhsmart commented on app/v1_router.py
> +api_v1_router.include_router(
Bỏ

2022-08-30 02:52 UTC, namvhsmart commented on tests/test_overview_page.py
> +
Bổ sung test case trắng db

2022-08-30 07:28 UTC, cuongtv-smartosc commented
Close

2022-08-30 07:29 UTC, closed without merging